# All the default Shellos aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/shellos/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'

# Editor alias
alias snano='sudo nano'

# Run fastfetch on shell initialization
fastfetch