source $SHELLOS_INSTALL/scripts/presentation.sh
source $SHELLOS_INSTALL/scripts/errors.sh
source $SHELLOS_INSTALL/scripts/logging.sh
source $SHELLOS_INSTALL/scripts/guard.sh
run_logged $SHELLOS_INSTALL/scripts/pacman.sh
run_logged $SHELLOS_INSTALL/scripts/migrations.sh
run_logged $SHELLOS_INSTALL/scripts/disable-mkinitcpio.sh
run_logged $SHELLOS_INSTALL/scripts/base.sh
run_logged $SHELLOS_INSTALL/scripts/lazyvim.sh
